# Generated by Django 4.2.3 on 2023-07-14 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
